/**
 * Design system: dark editorial travel journal with warm orange calls to action.
 * PickMe is framed as a locally built ride-hailing option, with clear boundaries between urban on-demand rides and pre-planned intercity travel.
 */
import { useEffect } from "react";
import { Link } from "wouter";
import { ArrowLeft, ArrowRight, Check, MapPinned, Smartphone, Timer, WalletCards } from "lucide-react";
import { MediaHeader } from "@/components/MediaHeader";

const ARTICLE_TITLE = "スリランカのPickMe完全ガイド｜使い方・Uber比較・都市間移動での注意点";
const hero = "/manus-storage/tuktuk-2_12590549.jpg";
const van = "/manus-storage/transport-van-thumb_7e18c597.png";
const faqs = [
  { question: "PickMeとは何ですか？", answer: "PickMeはスリランカ発の配車アプリです。公式サイトではRideをはじめ、Rentals、Food & Market、Truck、Flashなどのサービスを案内しています。" },
  { question: "PickMeは旅行者でも使えますか？", answer: "乗車場所と目的地を入力して配車を依頼する仕組みのため、都市部の短距離移動では利用を検討しやすいサービスです。利用できる地域、車種、配車状況、支払い条件はアプリ上で確認しましょう。" },
  { question: "PickMeとUberはどちらがおすすめですか？", answer: "都市部の短距離なら、出発地・目的地・車種・配車状況をアプリで見て、その時に使いやすい方を選ぶ方法が実用的です。重要なのは、都市間や周遊を同じ感覚で扱わず、旅程に合う手段を選ぶことです。" },
  { question: "PickMeよりタクシーチャーターが向くのはどんな場合ですか？", answer: "空港送迎、遠方への都市間移動、複数の観光地への立ち寄り、家族旅行、荷物が多い日、帰路まで含めて予定を決めたい場合は、タクシーチャーターが向いています。" },
];
function Heading({ label, children }: { label: string; children: React.ReactNode }) { return <div className="mt-16 mb-7 md:mt-20"><span className="font-montserrat text-[10px] font-bold tracking-[0.22em] uppercase" style={{ color: "#E8732A" }}>{label}</span><h2 className="font-serif-jp text-2xl md:text-3xl font-bold leading-relaxed text-white mt-3">{children}</h2></div>; }
function Figure({ src, alt, caption }: { src: string; alt: string; caption: string }) { return <figure><div className="h-64 md:h-80 overflow-hidden" style={{ backgroundColor: "#132434" }}><img src={src} alt={alt} className="w-full h-full object-cover" loading="lazy" /></div><figcaption className="mt-2 text-[11px] leading-relaxed" style={{ color: "#8EA0AE" }}>{caption}</figcaption></figure>; }
export default function ArticlePickMe() {
  useEffect(() => {
    document.title = ARTICLE_TITLE;
    const description = "スリランカの配車アプリPickMeの使い方、Uberとの違い、短距離利用のメリット、都市間移動の注意点、タクシーチャーターとの使い分けを解説します。";
    let meta = document.querySelector('meta[name="description"]') as HTMLMetaElement | null; if (!meta) { meta = document.createElement("meta"); meta.name = "description"; document.head.appendChild(meta); } meta.content = description;
    let keywords = document.querySelector('meta[name="keywords"]') as HTMLMetaElement | null; if (!keywords) { keywords = document.createElement("meta"); keywords.name = "keywords"; document.head.appendChild(keywords); } keywords.content = "スリランカ PickMe,PickMe 使い方,スリランカ 配車アプリ,スリランカ Uber,スリランカ 都市間移動,スリランカ タクシーチャーター";
    let canonical = document.getElementById("article-canonical") as HTMLLinkElement | null; if (!canonical) { canonical = document.createElement("link"); canonical.id = "article-canonical"; canonical.rel = "canonical"; document.head.appendChild(canonical); } canonical.href = "https://srilankataxicharter.com/articles/sri-lanka-pickme-guide";
    const id = "article-pickme-jsonld"; document.getElementById(id)?.remove(); const jsonLd = document.createElement("script"); jsonLd.id = id; jsonLd.type = "application/ld+json"; jsonLd.text = JSON.stringify({ "@context": "https://schema.org", "@graph": [{ "@type": "Article", headline: ARTICLE_TITLE, description, mainEntityOfPage: canonical.href, inLanguage: "ja", about: ["スリランカ", "PickMe", "配車アプリ"] }, { "@type": "FAQPage", mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) }] }); document.head.appendChild(jsonLd); return () => document.getElementById(id)?.remove();
  }, []);
  return <div className="min-h-screen" style={{ backgroundColor: "#0A1520", color: "#F0F4F8" }}><MediaHeader activeCategory="transport" /><main>
    <section className="relative overflow-hidden" style={{ minHeight: "min(680px, 78svh)" }}><img src={hero} alt="スリランカのトゥクトゥクを利用する旅行者" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0" style={{ background: "linear-gradient(90deg, rgba(7,16,26,0.96) 0%, rgba(7,16,26,0.75) 50%, rgba(7,16,26,0.18) 100%), linear-gradient(0deg, #0A1520 0%, transparent 38%)" }} /><div className="relative z-10 max-w-6xl mx-auto px-5 md:px-8 min-h-[inherit] flex items-end pb-16 md:pb-20"><div className="max-w-3xl"><Link href="/articles?category=transport" className="inline-flex items-center gap-2 mb-8 text-xs font-montserrat font-bold tracking-[0.12em] hover:text-white" style={{ color: "#B8C5D0" }}><ArrowLeft size={14} /> 移動手段の記事一覧へ</Link><div className="flex items-center gap-3 mb-5"><span className="h-px w-12" style={{ backgroundColor: "#E8732A" }} /><span className="font-montserrat text-[10px] font-bold tracking-[0.24em]" style={{ color: "#F1A368" }}>PICKME GUIDE · 09</span></div><h1 className="font-serif-jp text-3xl sm:text-4xl md:text-5xl font-semibold leading-[1.35] text-white mb-5">{ARTICLE_TITLE}</h1><p className="font-sans text-sm md:text-base leading-8 max-w-2xl" style={{ color: "#D5E0E7" }}>現地発の配車アプリPickMe。都市部での短距離利用に役立つ基本と、長距離で気をつけたい点をまとめます。</p><div className="flex items-center gap-4 mt-7 text-[11px] font-montserrat tracking-[0.1em]" style={{ color: "#B8C5D0" }}><span>移動手段</span><span className="h-px w-5 bg-white/30" /><span>読了約8分</span></div></div></div></section>
    <article className="max-w-3xl mx-auto px-5 md:px-8 pb-20 md:pb-28"><div className="border-b py-9 md:py-11" style={{ borderColor: "rgba(255,255,255,0.14)" }}><p className="font-serif-jp text-lg md:text-xl leading-9" style={{ color: "#DCE6EC" }}>PickMeは、スリランカ発の配車アプリです。町なかで車やトゥクトゥクを探したいとき、乗車場所と目的地を入力して配車を依頼する方法として、個人旅行でも候補になります。</p><p className="font-serif-jp text-lg md:text-xl leading-9 mt-5" style={{ color: "#DCE6EC" }}>短距離を気軽に移動するためのアプリとしては便利ですが、空港から遠方へ向かう日、都市間をまたぐ日、複数の観光地へ立ち寄る日まで、オンデマンド配車だけに任せるのは慎重に考えたいところです。</p></div>
      <Heading label="THE SHORT ANSWER">まずは結論：PickMeは都市部の短距離で活用。長距離は旅程を事前に固める</Heading><div className="grid sm:grid-cols-3 gap-4">{[[<Smartphone size={20} />, "現地発の配車アプリ", "PickMeはRide、Rentalsなどを案内するスリランカ発のサービスです。"], [<MapPinned size={20} />, "町なかの移動に便利", "ホテルからレストラン、観光地間の短距離移動で選択肢になります。"], [<Timer size={20} />, "重要な日は別手段も比較", "遠方・早朝・複数立ち寄りは、配車状況だけに依存しない計画が安心です。"]].map(([icon, title, text]) => <div key={title as string} className="border p-5 md:p-6" style={{ borderColor: "rgba(255,255,255,0.14)", backgroundColor: "rgba(255,255,255,0.025)" }}><div className="mb-4" style={{ color: "#E8732A" }}>{icon}</div><h2 className="font-serif-jp text-lg font-bold text-white mb-2">{title}</h2><p className="font-sans text-sm leading-7" style={{ color: "#B8C5D0" }}>{text}</p></div>)}</div>
      <Heading label="WHAT IS PICKME">PickMeとは？スリランカ旅行で知っておきたい配車アプリ</Heading><p className="font-sans text-[15px] md:text-base leading-8" style={{ color: "#C7D3DB" }}>PickMeは、スリランカ発のソフトウェアサービスで、公式サイトではRide、Rentals、Food & Market、Truck、Flashなどを提供しています。[1] 旅行者にとっては、まずRideが移動手段として関係します。アプリで出発地と目的地を入力し、その時点での車種や配車状況を確認しながら利用を検討できます。</p><div className="grid sm:grid-cols-2 gap-5 mt-8"><Figure src={hero} alt="スリランカの町でトゥクトゥクを利用する旅行者" caption="PickMeのような配車アプリは、町なかの短距離移動を手配する選択肢です。" /><Figure src={van} alt="スリランカ個人旅行で使えるシルバーのバン" caption="荷物や旅程を確定したい日は、専用車のような事前手配も比較します。" /></div>
      <Heading label="HOW TO USE">PickMeの使い方：利用前に確認したい4つのこと</Heading><div className="mt-7 border" style={{ borderColor: "rgba(232,115,42,0.42)", backgroundColor: "rgba(232,115,42,0.06)" }}>{[["01", "現在地と目的地を確認", "ホテル名だけでなく、地図上の乗車場所と目的地が正しいかを確認します。"], ["02", "車種・料金・配車状況を見る", "短距離の移動では、選べる車種と料金の目安を見ながら依頼を検討します。"], ["03", "通信環境と連絡手段を用意", "空港・ホテル・街なかでアプリを使えるよう、SIMやWi-Fiなどを準備します。"], ["04", "目的地に着くまでの予定を確認", "遅い時間や次の集合がある場合は、配車が見つからない時の代替案も考えます。"]].map(([number, title, text], index) => <div key={number} className={`grid md:grid-cols-[54px_1fr] gap-3 px-5 py-5 ${index > 0 ? "border-t" : ""}`} style={{ borderColor: "rgba(255,255,255,0.12)" }}><span className="font-montserrat text-xs font-bold tracking-[0.16em]" style={{ color: "#E8732A" }}>{number}</span><div><h2 className="font-serif-jp font-bold text-white mb-2">{title}</h2><p className="font-sans text-sm leading-7" style={{ color: "#C7D3DB" }}>{text}</p></div></div>)}</div>
      <Heading label="PICKME OR UBER">PickMeとUber、どちらを使う？</Heading><p className="font-sans text-[15px] md:text-base leading-8" style={{ color: "#C7D3DB" }}>都市部の短距離移動では、PickMeとUberを同時に確認し、その時に利用できる車種、料金の目安、配車状況で選ぶ方法が実用的です。どちらか一方にこだわるより、目的地・時間・荷物に合うかを見ながら使い分けましょう。</p><div className="overflow-x-auto border mt-7" style={{ borderColor: "rgba(255,255,255,0.15)" }}><table className="w-full min-w-[710px] text-left"><thead style={{ backgroundColor: "rgba(232,115,42,0.12)" }}><tr className="font-montserrat text-[11px] tracking-[0.12em]" style={{ color: "#F1A368" }}><th className="px-5 py-4">手段</th><th className="px-5 py-4">向く場面</th><th className="px-5 py-4">メリット</th><th className="px-5 py-4">注意点</th></tr></thead><tbody className="font-sans text-sm" style={{ color: "#D7E0E6" }}><tr className="border-t" style={{ borderColor: "rgba(255,255,255,0.1)" }}><td className="px-5 py-4 font-bold">PickMe</td><td className="px-5 py-4">都市部の短距離</td><td className="px-5 py-4">現地発アプリとしてRide等を利用できる</td><td className="px-5 py-4">配車状況・通信環境を確認</td></tr><tr className="border-t" style={{ borderColor: "rgba(255,255,255,0.1)" }}><td className="px-5 py-4 font-bold">Uber</td><td className="px-5 py-4">都市部の短距離・条件が合う都市間</td><td className="px-5 py-4">都市間向けIntercityも案内されている</td><td className="px-5 py-4">承諾・追加費用・配車条件</td></tr><tr className="border-t" style={{ borderColor: "rgba(255,255,255,0.1)" }}><td className="px-5 py-4 font-bold" style={{ color: "#F1A368" }}>タクシーチャーター</td><td className="px-5 py-4">空港・都市間・観光周遊</td><td className="px-5 py-4">車種・立ち寄り・料金条件を事前に相談できる</td><td className="px-5 py-4">見積もり範囲を確認</td></tr></tbody></table></div>
      <Heading label="WHY CHARTER FOR LONG DISTANCE">都市間移動でPickMeだけに頼りにくい理由</Heading><div className="space-y-4">{[["重要な移動日に配車状況を待ちたくない", "空港の到着日、早朝出発、サファリや列車の集合がある日には、配車が見つかるかを当日に判断するより、事前手配の方が予定を組みやすくなります。"], ["途中の立ち寄りを旅程として固定したい", "遺跡、食事、展望台、ホテル移動を一日に入れる場合は、停車・待機・帰路までを事前に相談できる方が効率的です。"], ["荷物・家族・長距離を一台でまとめたい", "人数とスーツケースに合う車種を選び、出発から到着までを一本の予定にすることで、移動の負担を抑えられます。"]].map(([title, text]) => <div key={title} className="grid md:grid-cols-[44px_1fr] gap-3 border-l-2 py-4 pl-5" style={{ borderColor: "#E8732A" }}><WalletCards size={18} className="mt-1" style={{ color: "#E8732A" }} /><div><h2 className="font-serif-jp font-bold text-white mb-2">{title}</h2><p className="font-sans text-sm leading-7" style={{ color: "#C7D3DB" }}>{text}</p></div></div>)}</div>
      <Heading label="FAQ">スリランカのPickMeでよくある質問</Heading><div className="divide-y border-y" style={{ borderColor: "rgba(255,255,255,0.14)" }}>{faqs.map((faq, index) => <details key={faq.question} className="group py-5"><summary className="cursor-pointer list-none flex items-start gap-4 font-serif-jp font-bold text-white"><span className="font-montserrat text-[10px] tracking-[0.16em] mt-1" style={{ color: "#E8732A" }}>Q{String(index + 1).padStart(2, "0")}</span><span className="flex-1 leading-7">{faq.question}</span><span className="text-xl leading-none transition-transform group-open:rotate-45" style={{ color: "#E8732A" }}>+</span></summary><p className="font-sans text-sm leading-8 mt-4 pl-10" style={{ color: "#C7D3DB" }}>{faq.answer}</p></details>)}</div>
      <section className="relative overflow-hidden mt-16 md:mt-20 p-7 md:p-10 border" style={{ borderColor: "rgba(232,115,42,0.55)", background: "linear-gradient(110deg, rgba(232,115,42,0.16), rgba(201,168,76,0.10) 48%, rgba(9,22,34,0.65)), #102132" }}><div className="absolute inset-0 opacity-20" style={{ backgroundImage: "linear-gradient(90deg, rgba(255,255,255,0.06) 1px, transparent 1px), linear-gradient(rgba(255,255,255,0.06) 1px, transparent 1px)", backgroundSize: "22px 22px" }} /><div className="relative z-10 max-w-2xl"><div className="flex items-center gap-3 mb-4"><span className="h-px w-10" style={{ backgroundColor: "#E8732A" }} /><span className="font-montserrat text-[10px] font-bold tracking-[0.22em]" style={{ color: "#F1A368" }}>PLAN BEYOND THE CITY</span></div><h2 className="font-serif-jp text-2xl md:text-3xl font-bold text-white leading-relaxed">都市を越える日は、<br />旅程を先に整えよう。</h2><p className="font-sans text-sm md:text-base leading-8 mt-5" style={{ color: "#D7E1E7" }}>料金の分かりやすさ、日本語対応、ドライバー品質、キャンセル条件を比べて、スリランカ個人旅行に合うタクシーチャーターを選びませんか。</p><a href="/#ranking" className="inline-flex items-center gap-3 mt-7 px-6 py-4 font-montserrat text-xs font-bold tracking-[0.12em] text-white transition-transform hover:-translate-y-0.5" style={{ backgroundColor: "#E8732A", boxShadow: "0 12px 26px rgba(0,0,0,0.25)" }}>タクシーチャーターおすすめ3選を比較する <ArrowRight size={15} /></a></div></section>
      <section className="mt-14 border-t pt-8" style={{ borderColor: "rgba(255,255,255,0.14)" }}><h2 className="font-serif-jp text-lg font-bold text-white mb-4">参考情報</h2><ol className="space-y-2 font-sans text-xs leading-6" style={{ color: "#9BAAB5" }}><li>[1] <a className="underline underline-offset-4 hover:text-white" href="https://pickme.lk/" target="_blank" rel="noopener noreferrer">PickMe公式サイト</a></li></ol></section>
    </article></main></div>;
}
