/**
 * Design system: dark editorial travel journal with warm orange calls to action.
 * Uber is explained as a helpful on-demand tool, while the article clarifies the operational uncertainty of long-distance and multi-stop travel.
 */
import { useEffect } from "react";
import { Link } from "wouter";
import { AlertTriangle, ArrowLeft, ArrowRight, Check, MapPinned, Smartphone, Timer } from "lucide-react";
import { MediaHeader } from "@/components/MediaHeader";

const ARTICLE_TITLE = "スリランカでUBERは実用的？都市間移動も可能？";
const hero = "/manus-storage/charter-1_ee4f51c5.png";
const van = "/manus-storage/transport-van-thumb_7e18c597.png";
const faqs = [
  { question: "スリランカでUberは使えますか？", answer: "Uberはスリランカ向けに配車サービスを提供しており、都市間向けのUber Intercityも公式に案内されています。実際に利用できる車種や配車状況は、出発地・目的地・時間帯をアプリで確認しましょう。" },
  { question: "Uberで都市間移動はできますか？", answer: "Uber Intercityは都市間の移動向けに案内されています。ただし、公式案内ではドライバーがリクエストを承諾する保証はないと明記されています。到着時刻が重要な日や遠方への移動は、事前確定できる手段も比較しましょう。" },
  { question: "Uberの表示料金だけで移動できますか？", answer: "Uber Intercityの公式案内では、アプリに表示される事前運賃に通行料・税金が含まれず、追加でドライバーへ支払う必要がある場合があると記載されています。予約前に条件を確認しましょう。" },
  { question: "Uberよりタクシーチャーターが向くのはどんな場合ですか？", answer: "空港送迎、都市間移動、複数の立ち寄り、家族旅行、大きな荷物がある日、帰路まで含めて予定を確定したい場合は、車種・料金条件・旅程を事前に相談できるタクシーチャーターが向いています。" },
];
function Heading({ label, children }: { label: string; children: React.ReactNode }) { return <div className="mt-16 mb-7 md:mt-20"><span className="font-montserrat text-[10px] font-bold tracking-[0.22em] uppercase" style={{ color: "#E8732A" }}>{label}</span><h2 className="font-serif-jp text-2xl md:text-3xl font-bold leading-relaxed text-white mt-3">{children}</h2></div>; }
function Figure({ src, alt, caption }: { src: string; alt: string; caption: string }) { return <figure><div className="h-64 md:h-80 overflow-hidden" style={{ backgroundColor: "#132434" }}><img src={src} alt={alt} className="w-full h-full object-cover" loading="lazy" /></div><figcaption className="mt-2 text-[11px] leading-relaxed" style={{ color: "#8EA0AE" }}>{caption}</figcaption></figure>; }
export default function ArticleUber() {
  useEffect(() => {
    document.title = ARTICLE_TITLE;
    const description = "スリランカでUberは実用的？都市部・都市間でのUber Intercityのメリットと注意点、料金・配車・追加費用・長距離利用のデメリット、タクシーチャーターとの使い分けを解説します。";
    let meta = document.querySelector('meta[name="description"]') as HTMLMetaElement | null; if (!meta) { meta = document.createElement("meta"); meta.name = "description"; document.head.appendChild(meta); } meta.content = description;
    let keywords = document.querySelector('meta[name="keywords"]') as HTMLMetaElement | null; if (!keywords) { keywords = document.createElement("meta"); keywords.name = "keywords"; document.head.appendChild(keywords); } keywords.content = "スリランカ Uber,スリランカ Uber 都市間,スリランカ Uber Intercity,スリランカ 配車アプリ,スリランカ タクシーチャーター";
    let canonical = document.getElementById("article-canonical") as HTMLLinkElement | null; if (!canonical) { canonical = document.createElement("link"); canonical.id = "article-canonical"; canonical.rel = "canonical"; document.head.appendChild(canonical); } canonical.href = "https://srilankataxicharter.com/articles/sri-lanka-uber-guide";
    const id = "article-uber-jsonld"; document.getElementById(id)?.remove(); const jsonLd = document.createElement("script"); jsonLd.id = id; jsonLd.type = "application/ld+json"; jsonLd.text = JSON.stringify({ "@context": "https://schema.org", "@graph": [{ "@type": "Article", headline: ARTICLE_TITLE, description, mainEntityOfPage: canonical.href, inLanguage: "ja", about: ["スリランカ", "Uber", "都市間移動"] }, { "@type": "FAQPage", mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) }] }); document.head.appendChild(jsonLd); return () => document.getElementById(id)?.remove();
  }, []);
  return <div className="min-h-screen" style={{ backgroundColor: "#0A1520", color: "#F0F4F8" }}><MediaHeader activeCategory="transport" /><main>
    <section className="relative overflow-hidden" style={{ minHeight: "min(680px, 78svh)" }}><img src={hero} alt="スリランカでの都市間移動に使える車両" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0" style={{ background: "linear-gradient(90deg, rgba(7,16,26,0.96) 0%, rgba(7,16,26,0.75) 50%, rgba(7,16,26,0.18) 100%), linear-gradient(0deg, #0A1520 0%, transparent 38%)" }} /><div className="relative z-10 max-w-6xl mx-auto px-5 md:px-8 min-h-[inherit] flex items-end pb-16 md:pb-20"><div className="max-w-3xl"><Link href="/articles/transport" className="inline-flex items-center gap-2 mb-8 text-xs font-montserrat font-bold tracking-[0.12em] hover:text-white" style={{ color: "#B8C5D0" }}><ArrowLeft size={14} /> 移動手段の記事一覧へ</Link><div className="flex items-center gap-3 mb-5"><span className="h-px w-12" style={{ backgroundColor: "#E8732A" }} /><span className="font-montserrat text-[10px] font-bold tracking-[0.24em]" style={{ color: "#F1A368" }}>UBER GUIDE · 07</span></div><h1 className="font-serif-jp text-3xl sm:text-4xl md:text-5xl font-semibold leading-[1.35] text-white mb-5">{ARTICLE_TITLE}</h1><p className="font-sans text-sm md:text-base leading-8 max-w-2xl" style={{ color: "#D5E0E7" }}>アプリで気軽に呼べるUber。都市部では便利な一方、長距離や周遊では知っておきたい条件があります。</p><div className="flex items-center gap-4 mt-7 text-[11px] font-montserrat tracking-[0.1em]" style={{ color: "#B8C5D0" }}><span>移動手段</span><span className="h-px w-5 bg-white/30" /><span>読了約8分</span></div></div></div></section>
    <article className="max-w-3xl mx-auto px-5 md:px-8 pb-20 md:pb-28"><div className="border-b py-9 md:py-11" style={{ borderColor: "rgba(255,255,255,0.14)" }}><p className="font-serif-jp text-lg md:text-xl leading-9" style={{ color: "#DCE6EC" }}>Uberは、スリランカの都市部で短距離を移動するときに便利な選択肢です。行き先と料金の目安をアプリで見ながら、必要なときに配車を依頼できるため、流しのタクシーやトゥクトゥクを探す手間を減らせます。</p><p className="font-serif-jp text-lg md:text-xl leading-9 mt-5" style={{ color: "#DCE6EC" }}>ただし、都市間・長距離・複数観光地を回る移動まで、Uberだけで完結させるのは別の話です。便利なメリットを活かしつつ、重要な移動日はタクシーチャーターを比較する方が、旅程を安定させやすくなります。</p></div>
      <Heading label="THE SHORT ANSWER">まずは結論：Uberは都市部の短距離に便利。都市間は条件をよく確認する</Heading><div className="grid sm:grid-cols-3 gap-4">{[[<Smartphone size={20} />, "料金の目安を見やすい", "目的地を入力して、配車前に料金や車種の目安を確認しやすい点がメリットです。"], [<MapPinned size={20} />, "都市間サービスもある", "Uber Intercityはスリランカ向けに都市間移動サービスとして公式に案内されています。"], [<Timer size={20} />, "重要な日は確定性を比較", "公式でもドライバーの承諾は保証されないため、時間が重要な日は別手段も比較します。"]].map(([icon, title, text]) => <div key={title as string} className="border p-5 md:p-6" style={{ borderColor: "rgba(255,255,255,0.14)", backgroundColor: "rgba(255,255,255,0.025)" }}><div className="mb-4" style={{ color: "#E8732A" }}>{icon}</div><h2 className="font-serif-jp text-lg font-bold text-white mb-2">{title}</h2><p className="font-sans text-sm leading-7" style={{ color: "#B8C5D0" }}>{text}</p></div>)}</div>
      <Heading label="UBER MERITS">スリランカでUberを使うメリット</Heading><p className="font-sans text-[15px] md:text-base leading-8" style={{ color: "#C7D3DB" }}>都市部のホテルからレストランへ、買い物の帰り、短〜中距離の移動などでは、Uberは手軽です。行き先を入力して配車依頼を出せるため、住所や地名の説明に不安があるときにも役立ちます。Uber Intercityでは、Zip、Premier、Minivan、Vanといった選択肢が案内されており、都市間の利用も視野に入れられます。[1]</p>
      <Heading label="THE LIMITS">都市間移動でUberをおすすめしにくい理由</Heading><div className="space-y-4">{[["配車が確定するまで予定を固定しにくい", "Uber Intercityの公式案内では、ドライバーがリクエストを承諾する保証はないと明記されています。早朝の出発、空港到着、サファリの集合など、時間が重要な日は不確実性になります。"], ["表示運賃以外の費用を確認する必要がある", "公式案内では、事前表示の運賃に通行料・税金が含まれず、追加でドライバーに現金支払いが必要になる場合があるとされています。"], ["途中の立ち寄りを一日の旅程として組みにくい", "遺跡、食事、展望台、ホテル移動を一日にまとめる場合、停車・待機・帰路までを事前に相談できる方が、予定を把握しやすくなります。"], ["遠方で帰りの移動を確保しにくいことがある", "地方の観光地では、行きの配車だけでなく、帰りの車両や次のホテルへの移動まで含めて考える必要があります。"]].map(([title, text]) => <div key={title} className="grid md:grid-cols-[52px_1fr] gap-4 border-l-2 py-4 pl-5" style={{ borderColor: "#E8732A" }}><AlertTriangle size={19} className="mt-1" style={{ color: "#E8732A" }} /><div><h2 className="font-serif-jp font-bold text-white mb-2">{title}</h2><p className="font-sans text-sm leading-7" style={{ color: "#C7D3DB" }}>{text}</p></div></div>)}</div>
      <Heading label="UBER OR CHARTER">Uber・都市間Uber・タクシーチャーターの使い分け</Heading><div className="overflow-x-auto border" style={{ borderColor: "rgba(255,255,255,0.15)" }}><table className="w-full min-w-[710px] text-left"><thead style={{ backgroundColor: "rgba(232,115,42,0.12)" }}><tr className="font-montserrat text-[11px] tracking-[0.12em]" style={{ color: "#F1A368" }}><th className="px-5 py-4">手段</th><th className="px-5 py-4">向く場面</th><th className="px-5 py-4">主なメリット</th><th className="px-5 py-4">確認したい点</th></tr></thead><tbody className="font-sans text-sm" style={{ color: "#D7E0E6" }}><tr className="border-t" style={{ borderColor: "rgba(255,255,255,0.1)" }}><td className="px-5 py-4 font-bold">Uber</td><td className="px-5 py-4">都市部の短〜中距離</td><td className="px-5 py-4">アプリで目的地・料金目安を確認しやすい</td><td className="px-5 py-4">配車状況・通信環境</td></tr><tr className="border-t" style={{ borderColor: "rgba(255,255,255,0.1)" }}><td className="px-5 py-4 font-bold">Uber Intercity</td><td className="px-5 py-4">単純な都市間片道</td><td className="px-5 py-4">都市間向けの車種を選べる</td><td className="px-5 py-4">承諾・追加費用・帰路</td></tr><tr className="border-t" style={{ borderColor: "rgba(255,255,255,0.1)" }}><td className="px-5 py-4 font-bold" style={{ color: "#F1A368" }}>タクシーチャーター</td><td className="px-5 py-4">空港・周遊・複数立ち寄り・家族旅行</td><td className="px-5 py-4">車種・旅程・料金条件を事前に相談できる</td><td className="px-5 py-4">見積もりに含まれる内容</td></tr></tbody></table></div>
      <Heading label="WHEN CHARTER MAKES SENSE">スリランカで都市間移動するなら、タクシーチャーターが適切な4つのケース</Heading><div className="grid md:grid-cols-[0.95fr_1.05fr] gap-7 items-start"><Figure src={van} alt="スリランカ個人旅行で使えるシルバーのバン" caption="荷物・複数の立ち寄り・到着時間を重視する日は、専用車が旅程を支えます。" /><div><ul className="space-y-4 font-sans text-sm leading-7" style={{ color: "#C7D3DB" }}>{["空港からシーギリヤ、キャンディ、ゴールなど遠方のホテルへ直接向かう。", "遺跡・食事・展望台・ホテル移動を一日に組み込む。", "家族旅行・子ども連れ・スーツケースが多い。", "早朝出発や集合時刻があり、配車の承諾待ちを避けたい。"].map((item) => <li key={item} className="flex gap-3"><Check size={17} className="shrink-0 mt-1" style={{ color: "#E8732A" }} />{item}</li>)}</ul><p className="font-sans text-[15px] leading-8 mt-7" style={{ color: "#C7D3DB" }}>Uberのメリットは、必要なときに短距離を気軽に移動できることです。ただし、旅の重要な移動日までオンデマンド配車に任せるより、車種・合流・立ち寄り・料金を事前に決められるタクシーチャーターを選ぶ方が、スムーズに進めやすいでしょう。</p>
          <p className="font-sans text-[15px] md:text-base leading-8 mt-5" style={{ color: "#C7D3DB" }}>Uberと現地発アプリの違いを確認したい方は、<Link href="/articles/sri-lanka-pickme-guide" className="underline decoration-[#E8732A] underline-offset-4 hover:text-white">PickMe完全ガイド</Link>も参照してください。列車・バス・トゥクトゥク・専用車も含めて選ぶなら、<Link href="/articles/sri-lanka-transport-guide" className="underline decoration-[#E8732A] underline-offset-4 hover:text-white">スリランカの移動手段を比較する総合ガイド</Link>が役立ちます。</p></div></div>
      <Heading label="FAQ">スリランカのUberでよくある質問</Heading><div className="divide-y border-y" style={{ borderColor: "rgba(255,255,255,0.14)" }}>{faqs.map((faq, index) => <details key={faq.question} className="group py-5"><summary className="cursor-pointer list-none flex items-start gap-4 font-serif-jp font-bold text-white"><span className="font-montserrat text-[10px] tracking-[0.16em] mt-1" style={{ color: "#E8732A" }}>Q{String(index + 1).padStart(2, "0")}</span><span className="flex-1 leading-7">{faq.question}</span><span className="text-xl leading-none transition-transform group-open:rotate-45" style={{ color: "#E8732A" }}>+</span></summary><p className="font-sans text-sm leading-8 mt-4 pl-10" style={{ color: "#C7D3DB" }}>{faq.answer}</p></details>)}</div>

          <section className="relative overflow-hidden mt-16 md:mt-20 p-7 md:p-10 border" style={{ borderColor: "rgba(232,115,42,0.55)", background: "linear-gradient(110deg, rgba(232,115,42,0.16), rgba(201,168,76,0.10) 48%, rgba(9,22,34,0.65)), #102132" }}><div className="absolute inset-0 opacity-20" style={{ backgroundImage: "linear-gradient(90deg, rgba(255,255,255,0.06) 1px, transparent 1px), linear-gradient(rgba(255,255,255,0.06) 1px, transparent 1px)", backgroundSize: "22px 22px" }} /><div className="relative z-10 max-w-2xl"><div className="flex items-center gap-3 mb-4"><span className="h-px w-10" style={{ backgroundColor: "#E8732A" }} /><span className="font-montserrat text-[10px] font-bold tracking-[0.22em]" style={{ color: "#F1A368" }}>MAKE THE LONG MOVE SIMPLE</span></div><h2 className="font-serif-jp text-2xl md:text-3xl font-bold text-white leading-relaxed">重要な移動日は、<br />事前に条件を確定しよう。</h2><p className="font-sans text-sm md:text-base leading-8 mt-5" style={{ color: "#D7E1E7" }}>料金の分かりやすさ、日本語対応、ドライバー品質、キャンセル条件を比べて、都市間移動に合うタクシーチャーターを選びませんか。</p><a href="/#ranking" className="inline-flex items-center gap-3 mt-7 px-6 py-4 font-montserrat text-xs font-bold tracking-[0.12em] text-white transition-transform hover:-translate-y-0.5" style={{ backgroundColor: "#E8732A", boxShadow: "0 12px 26px rgba(0,0,0,0.25)" }}>タクシーチャーターおすすめ3選を比較する <ArrowRight size={15} /></a></div></section>
      <section className="mt-14 border-t pt-8" style={{ borderColor: "rgba(255,255,255,0.14)" }}><h2 className="font-serif-jp text-lg font-bold text-white mb-4">参考情報</h2><ol className="space-y-2 font-sans text-xs leading-6" style={{ color: "#9BAAB5" }}><li>[1] <a className="underline underline-offset-4 hover:text-white" href="https://www.uber.com/lk/en/ride/intercity/" target="_blank" rel="noopener noreferrer">Uber Intercity Sri Lanka</a></li></ol></section>
    </article></main></div>;
}
