/**
 * Design system: dark editorial travel guide with warm orange planning accents.
 * The articles use generated diagrams as explanatory figures inside the body, not as decorative end-of-page assets.
 */
import { useEffect } from "react";
import { ArrowLeft, ArrowRight, CalendarCheck, Check, Compass, FileCheck2, MapPinned } from "lucide-react";
import { Link } from "wouter";
import { MediaHeader } from "@/components/MediaHeader";

type Figure = { src: string; alt: string; caption: string; title: string; text: string };
type Section = { label: string; title: string; body: string[]; image?: { src: string; alt: string; caption: string }; table?: { headers: string[]; rows: string[][] }; links?: Related[] };
type Related = { before: string; text: string; href: string; after: string };
type Ref = { label: string; href: string };
type Guide = { number: string; slug: string; title: string; description: string; keywords: string; readingTime?: string; hero: { src: string; alt: string; caption: string }; intro: string[]; route: string[]; figure: Figure; sections: Section[]; checklist: { title: string; body: string; items: string[] }; related: Related[]; faqs: { question: string; answer: string }[]; references: Ref[] };

const guides: Record<"preparation" | "season", Guide> = {
  preparation: {
    number: "21",
    slug: "sri-lanka-independent-travel-preparation-guide",
    title: "スリランカ個人旅行の準備完全ガイド｜出発前に必要なことを時系列で解説",
    description: "スリランカ個人旅行の準備を時系列で解説。ETA、パスポート、航空券、ホテル、通信、海外旅行保険、空港送迎、都市間移動まで、出発前に確認したいことを整理します。",
    keywords: "スリランカ 個人旅行 準備,スリランカ旅行 準備,スリランカ ETA,スリランカ 空港送迎",
    hero: { src: "/manus-storage/article-airport-transfer-hero_fd800259.jpg", alt: "コロンボ空港で到着客を待つ専用車", caption: "個人旅行の準備は、入国書類と同じくらい、到着後の移動を決めておくことが大切です。" },
    intro: [
      "スリランカの個人旅行は、行き先が決まったら航空券とホテルだけを予約して終わりではありません。ETA、パスポートの有効期限、通信、保険、空港からの移動、都市間の移動方法を順番に決めることで、現地での判断を減らし、観光に使える時間を増やせます。",
      "このガイドでは、出発の数か月前から当日までを五つの段階に分け、個人手配で確認したい項目を整理します。すべてを完璧に準備するより、先に確定すべきことと、出発直前に再確認すべきことを分けるのがポイントです。",
    ],
    route: ["行き先を決める", "ETA・航空券", "ホテル・移動", "通信・保険", "出発当日"],
    figure: { src: "/manus-storage/sri-lanka-preparation-timeline_f73b2f7a.png", alt: "スリランカ個人旅行の出発前準備を示す時系列図", caption: "図：個人旅行の準備は、一度に片付けるのではなく、出発日から逆算して段階的に進めます。", title: "まず全体像を把握する：出発前の準備タイムライン", text: "ETAやパスポートのように早めに確認すべきものと、送迎の合流場所や荷造りのように直前で確定するものを分けると、準備が整理しやすくなります。" },
    sections: [
      { label: "STEP 01", title: "出発8〜12週間前：旅の軸を決め、パスポートとETAを確認する", body: ["最初に決めるのは、旅行日数、行きたい地域、入国・出国する空港です。シーギリヤ、キャンディ、高原、南部海岸を一度に入れる場合は、日数と移動距離を照らし合わせ、旅の主役を二つか三つに絞ります。", "スリランカ入国管理局は、観光・商用旅行者向けにETAを案内しています。パスポートは到着日から少なくとも6か月の有効期間を求める一般的な条件が示されているため、申請前に公式ETAサイトと、国籍・旅行目的に応じた最新の条件を必ず確認しましょう。"], image: { src: "/manus-storage/sri-lanka-preparation-timeline_f73b2f7a.png", alt: "出発前準備を時系列で示した図", caption: "STEP 01：早めに確認する書類と、直前に確定する送迎・荷造りを分けます。" } },
      { label: "STEP 02", title: "出発4〜6週間前：ホテルの位置と、都市間移動を同じ旅程で考える", body: ["ホテルは、料金や雰囲気だけでなく、到着日と出発日の移動を基準に選びます。空港到着後に遠方へ向かうのか、ネゴンボやコロンボで一泊するのか。シーギリヤ、キャンディ、エッラ、ゴールのどこに連泊するかを決めると、必要な車の手配日が見えてきます。", "個人旅行では、空港送迎、ホテル間の移動、紅茶列車の駅送迎を別々に探すより、旅程の節目を一本の流れとして考えるとスムーズです。荷物が多い日、早朝発の日、到着時間が重要な日は、事前手配の専用車を比較する価値があります。"] },
      { label: "STEP 03", title: "出発2週間前：通信・保険・お金の使い方を整える", body: ["現地で地図、ホテル連絡、配車、緊急時の確認ができるよう、SIMカードやeSIMなど通信手段を決めます。ホテル住所、ドライバーとの合流情報、旅程は、オフラインでも見られる状態にしておくと安心です。", "海外旅行保険の補償範囲、クレジットカードの利用可否、現金を使う場面も確認しましょう。すべての場面で同じ支払い方法に頼るのではなく、カード・現金・連絡手段を分けて準備すると、旅先での選択肢を残せます。"] },
      { label: "STEP 04", title: "出発3日前：到着日の動線と持ち物を最終確認する", body: ["航空券、ETAの承認内容、パスポート、ホテル予約、送迎の連絡先を一つのフォルダにまとめます。到着時刻、航空便名、人数、荷物の数、ホテル名を送迎担当へ伝える場合は、この段階で再確認しておきましょう。", "持ち物は、寺院を訪れる日の服、日差し対策、雨具、モバイルバッテリー、薬、常備品を旅程に照らして用意します。サファリ、高原、ビーチでは必要なものが異なるため、目的地ごとに小分けにすると荷物を扱いやすくなります。"] },
      { label: "STEP 05", title: "出発当日：空港へ向かう前に、最初の24時間だけを見直す", body: ["当日は、旅の全日程を見返すより、到着後の最初の24時間に必要な情報だけを手元に置きます。空港での通信手段、送迎の合流場所、ホテル名、翌朝の出発時間を確認すれば、フライト後の判断を小さくできます。", "到着日は予定を詰め込まず、ホテルまでの移動、食事、休息を優先します。初日を整えることで、2日目以降の世界遺産や列車旅を自分のペースで楽しめます。"] },
    ],
    checklist: { title: "出発前の最終チェックリスト", body: "出発直前は、新しい情報を増やすより、すでに決めた内容が実行できる状態かを確認します。下記を一つずつ確認し、同行者がいる場合は同じ情報を共有しましょう。", items: ["パスポートの有効期限、ETAの承認内容、航空券の氏名表記", "ホテル予約と初日・最終日の移動手段", "通信手段、海外旅行保険、カード・現金の準備", "寺院・高原・サファリに合わせた服装と持ち物", "緊急連絡先、ホテル住所、送迎担当との合流情報"] },
    related: [{ before: "到着日からホテルまでの移動を比較したい方は、", text: "コロンボ空港送迎は必要？", href: "/articles/colombo-airport-transfer-guide", after: "を確認してください。" }, { before: "旅程に合う車・列車・バスの役割を整理するなら、", text: "スリランカの移動手段は何が正解？", href: "/articles/sri-lanka-transport-guide", after: "が出発点になります。" }, { before: "必要日数ごとに旅程を検討するなら、", text: "スリランカ旅行5日間モデルコース", href: "/articles/sri-lanka-5-day-itinerary", after: "も参考にしてください。" }],
    faqs: [{ question: "スリランカ個人旅行の準備はいつから始めればよいですか？", answer: "行き先・パスポート・ETAなど早めに確認したい項目があるため、出発の8〜12週間前を目安に旅程の軸を決めると進めやすくなります。" }, { question: "スリランカ入国にETAは必要ですか？", answer: "観光・商用旅行者向けにETAが案内されています。国籍・旅行目的・渡航時点の条件により異なるため、出発前にスリランカ入国管理局と公式ETAサイトを必ず確認してください。" }, { question: "空港送迎は出発前に予約した方がよいですか？", answer: "必須ではありませんが、初めての個人旅行、深夜・早朝到着、遠方のホテル、荷物が多い場合は、事前に合流場所と車を決めておくと到着日の判断を減らせます。" }],
    references: [{ label: "Sri Lanka Department of Immigration and Emigration: General Information on Visa", href: "https://www.immigration.gov.lk/pages_e.php?id=14" }],
  },
  season: {
    number: "22",
    slug: "sri-lanka-best-time-to-visit-by-region",
    title: "スリランカ旅行のベストシーズンはいつ？地域別の気候とおすすめ時期",
    description: "スリランカ旅行のベストシーズンを地域別に解説。南西海岸、東海岸、文化三角地帯、高原の気候の考え方と、季節に合わせたモデルコースの選び方を紹介します。",
    keywords: "スリランカ ベストシーズン,スリランカ 旅行 気候,スリランカ 旅行 時期,スリランカ 南西海岸 東海岸",
    readingTime: "読了約18分",
    hero: { src: "/manus-storage/galle_46cff405.jpg", alt: "スリランカ南西海岸のゴール旧市街", caption: "スリランカでは、同じ時期でも、どの地域へ行くかで旅の組み立て方が変わります。" },
    intro: [
      "スリランカ旅行のベストシーズンを考えるときは、国全体を一つの天気として捉えないことが大切です。南西海岸、東海岸、文化三角地帯、高原では、雨・風・海況・体感温度の感じ方が異なります。行きたい場所と旅の目的を先に決め、その地域の季節に合わせて日程を組む方が、旅行の満足度を高めやすくなります。",
      "最初に結論を言うと、ゴール・ミリッサ・ベントタなど南西海岸を主役にするなら概ね12〜3月、トリンコマリー・ニラヴェリ・アルガンベイなど東海岸を主役にするなら概ね5〜9月が、海辺の旅を考える出発点です。これは「その月なら必ず晴れる」という意味ではなく、二つのモンスーンによって海岸ごとの条件が入れ替わるためです。",
      "一方で、世界遺産、紅茶列車、サファリ、祭り、高原滞在は、同じ月でも判断が変わります。海況を最優先する旅、遺跡を歩く旅、雨上がりの緑を楽しむ旅では、選ぶ地域もホテルの位置も異なります。旅行日が先に決まっている場合でも、主役の地域を選び直せば、年間を通じて旅を組み立てられます。",
      "ここでは、月別の目安を地域・目的・移動の三つの視点で整理します。短期的な天候、海況、道路状況、施設の営業、祭りの日程は毎年変わるため、出発前には必ず公式情報と現地の最新情報を確認してください。",
    ],
    route: ["旅の目的を決める", "月と地域を組み合わせる", "移動日を減らす", "直前の天候を確認する"],
    figure: { src: "/manus-storage/sri-lanka-season-compass_0505bbe5.png", alt: "スリランカの地域別・季節別の旅先選びを示す図", caption: "図：南西海岸、東海岸、文化三角地帯、高原は、同じ月でも旅の目的と確認したい条件が異なります。", title: "最初の一問は「何月？」ではなく「何を主役にする？」", text: "ビーチ、遺跡、高原、列車旅、サファリのどれを優先するかを決め、次にその地域の季節を見ます。最後にホテル間・駅・空港の移動を足すと、天候に振り回されにくい旅程になります。" },
    sections: [
      { label: "QUICK ANSWER", title: "スリランカのベストシーズンは、南西海岸なら12〜3月、東海岸なら5〜9月が基本", body: ["検索でよく見かける「12〜3月がベストシーズン」という答えは、コロンボ、ゴール、ミリッサなど南西海岸を中心に旅をする場合の目安です。この時期は南西側で乾いた日が期待しやすく、海辺のホテル滞在や旧市街の散策を主役にした旅程を考えやすくなります。", "日本の夏休みに当たる5〜9月は、南西側で雨の影響を受けることがある一方、東海岸や北部が候補になります。トリンコマリー、ニラヴェリ、アルガンベイなどの海辺や、文化三角地帯を旅の中心に置くと、季節の特徴に合わせやすくなります。", "ただし、ベストシーズンは旅行の可否を決める線引きではありません。短いスコールで済む日もあり、雨の時期には宿が選びやすくなることもあります。海水浴、サーフィン、シュノーケリング、ホエールウォッチングのように海況が大切な目的だけは、地域ごとの季節と直前の営業状況を慎重に確認しましょう。"], links: [{ before: "旅の主役を海岸・遺跡・高原から選ぶ前に、必要日数を整理するなら、", text: "スリランカ旅行に必要な日数は？", href: "/articles/sri-lanka-trip-duration-guide", after: "が出発点になります。" }] },
      { label: "MONTH BY MONTH", title: "月別早見表：休みが先に決まっている時の、地域の選び方", body: ["月別の目安は、旅行先を絞るための最初のヒントです。表は一般的な季節傾向をまとめたもので、日々の天候や海況を保証するものではありません。雨が多くなりやすい時期ほど、移動日を減らし、代替できる観光やホテルで休む時間を残すと旅程を調整しやすくなります。"], table: { headers: ["時期", "主役にしやすい地域・体験", "旅程を組むポイント", "確認したいこと"], rows: [["1〜3月", "南西海岸、ゴール、文化三角地帯、高原", "世界遺産・紅茶列車・南部海岸を周遊する王道ルートを組みやすい", "年末年始を含む繁忙期のホテル・列車・送迎"], ["4月", "文化体験、内陸の遺跡、短期滞在", "暑さと祝日を考え、早朝観光と休息を入れる", "新年行事に伴う店舗・交通の営業状況"], ["5〜9月", "東海岸、北部、文化三角地帯、サファリ", "東海岸を主役にし、南西海岸を無理に長く入れない", "海況、国立公園の開園、長距離移動の所要時間"], ["10〜11月", "都市・文化・ホテル滞在を組み合わせる旅", "移動距離を短くし、予定を一つに固定しすぎない", "雨・道路状況・施設営業・旅程の代替案"], ["12月", "南西海岸、文化三角地帯、高原", "南西側の周遊を始めやすい。到着日とホテル移動日に余白を持つ", "クリスマス・年末の宿泊条件と早めの予約"]] } },
      { label: "PURPOSE 01", title: "目的別に時期を決める：海、遺跡、紅茶列車、サファリは同じ答えではない", body: ["ビーチを主役にするなら、まず南西海岸と東海岸のどちらへ行きたいかを決めます。南西側のゴール・ミリッサ・ベントタを選ぶなら概ね12〜3月、東海岸のトリンコマリー・ニラヴェリ・アルガンベイを選ぶなら概ね5〜9月という二軸から検討すると、海況に合う地域を選びやすくなります。", "シーギリヤ、ダンブッラ、ポロンナルワなどの文化三角地帯は、海の季節とは別に、暑さと歩く時間を中心に考えます。どの月でも日差しが強い時間を避け、早朝のシーギリヤロック、昼の休憩、午後の寺院という順番にすると、体力と天候の両方に余白を残せます。", "紅茶列車・ヌワラエリヤ・エッラを主役にする場合は、列車が走るかだけでなく、霧、雨、朝晩の体感温度、駅からホテルまでの移動を一緒に考えます。緑の濃い雨上がりを楽しむ旅もできますが、写真や展望を優先するなら、出発直前の予報と代替日の有無を確認しましょう。", "サファリは国立公園ごとに動物の動きや閉園期間が異なるため、月だけで決めません。希望する公園の公式情報を確認し、早朝サファリの前泊、終了後の長距離移動を避けることを優先します。天候の目安よりも、その日の開園状況と無理のない移動が重要です。"], links: [{ before: "紅茶列車を季節と移動に合わせて組みたい方は、", text: "紅茶列車に乗るスリランカ旅行モデルコース", href: "/articles/sri-lanka-tea-train-itinerary", after: "を確認してください。" }, { before: "ヤーラのサファリを旅程へ入れるなら、", text: "ヤーラ国立公園サファリを入れたモデルコース", href: "/articles/yala-national-park-safari-itinerary", after: "が参考になります。" }] },
      { label: "REGION 01", title: "南西海岸：ゴール・ベントタ・ミリッサを主役にするなら", body: ["スリランカ観光局は、北東風の時期には南西海岸が晴天になり、海が穏やかになる時期として11月から3月を案内しています。ゴール、ベントタ、ミリッサなどの海辺を主役にするなら、このような地域別の海況の違いを旅程づくりの出発点にしましょう。", "一方で、海辺の滞在は天候だけで決まりません。到着空港からの移動、ゴール旧市街を歩く時間、早朝アクティビティの有無を考え、ホテルの位置と車の手配日を決めると、海岸ドライブの時間を楽しみやすくなります。"], image: { src: "/manus-storage/galle_46cff405.jpg", alt: "南西海岸のゴール旧市街", caption: "南西海岸を主役にする旅では、ゴールの散策と海辺のホテル滞在を同じ流れで組み立てます。" } },
      { label: "REGION 02", title: "東海岸：海辺を楽しむなら、渡航時の風と海況を確認する", body: ["スリランカ観光局は、南西風の時期に東海岸の海が穏やかになると案内しています。南西海岸と東海岸では、同じ時期でも海の状態が異なるため、ビーチを旅の主役にする場合は、どちらの海岸を選ぶかを先に決めることが重要です。", "海辺のアクティビティを計画するときは、月の目安だけに頼らず、出発前に現地の天候・海況・営業状況を確認します。到着・出発の移動時間にも余白を取り、悪天候で予定を変える場合の代替案を用意しておくと安心です。"] },
      { label: "REGION 03", title: "文化三角地帯：シーギリヤ・ダンブッラは暑さと歩く時間を基準にする", body: ["シーギリヤ、ダンブッラ、ポロンナルワ、アヌラーダプラなどを回る旅では、海況よりも日差し・暑さ・徒歩観光の時間が旅の快適さを左右します。早朝にシーギリヤロックへ行き、暑い時間帯はホテルで休み、午後に寺院を訪れるように組むと、季節を問わず無理を抑えられます。", "遺跡が点在する地域では、短い雨や暑さに備え、飲み物、帽子、雨具、履き替えやすい靴を用意します。車は遺跡間の移動と荷物の保管に使い、観光地では歩く時間を確保する役割分担が向いています。"], image: { src: "/manus-storage/sigiriya-1_60f050bc.jpg", alt: "スリランカのシーギリヤロック", caption: "文化三角地帯では、暑さの強い時間を避けて世界遺産を巡る旅程にします。" } },
      { label: "REGION 04", title: "高原：紅茶列車・ヌワラエリヤ・エッラは、朝晩の準備も旅程に入れる", body: ["高原エリアでは、紅茶列車の乗車時間と、駅からホテルまでの移動を一緒に考えます。風景を楽しむ時間にしたい列車旅では、急なホテル移動を重ねず、降車駅からの送迎と荷物の扱いを先に整えるのがおすすめです。", "朝晩に肌寒く感じることもあるため、羽織るものを用意し、天候に合わせて展望・ハイキング・カフェの順番を調整します。雨で視界が変わることもあるため、列車や観光地の予定を一つに固定しすぎず、代替の時間を残すと旅を楽しみやすくなります。"], image: { src: "/manus-storage/train-1_47ef775a.jpg", alt: "スリランカ高原を走る紅茶列車", caption: "高原の旅は、紅茶列車の乗車と駅送迎を一つの流れとして計画します。" } },
      { label: "ROUTE DESIGN", title: "季節が読みにくいほど、移動日は短く、ホテル移動は少なくする", body: ["天候が不安定になりやすい時期は、観光地を減らすのではなく、ホテルを移る回数と長距離移動を減らします。朝に遺跡、午後に高原、夜に別都市という予定は、晴天でも余裕がなくなりやすく、雨や道路状況が変わったときに調整できません。到着日、ホテル移動日、早朝アクティビティの日は、予定を一つ少なくしましょう。", "特に空港、都市間、駅送迎、サファリ前後は、合流場所と到着時刻を事前に決めておくと、雨の中で車を探したり、荷物を持って乗り換えたりする負担を減らせます。公共交通や配車アプリを使う日と、長距離を専用車でつなぐ日を分ければ、費用と自由度のバランスも取りやすくなります。", "季節に適した場所を選ぶことと、移動を整えることは別の作業ではありません。南西海岸ならコロンボ空港からゴール、高原なら駅とホテル、文化三角地帯なら遺跡間の移動を先に決めることで、その日に晴れた時間を観光へ使いやすくなります。"], links: [{ before: "列車・バス・配車アプリ・専用車を季節と距離で使い分けるなら、", text: "スリランカの移動手段は何が正解？", href: "/articles/sri-lanka-transport-guide", after: "で比較できます。" }, { before: "南西海岸までを入れる王道の旅程は、", text: "スリランカ旅行7日間モデルコース", href: "/articles/sri-lanka-7-day-itinerary", after: "を参考にしてください。" }] },
    ],
    checklist: { title: "ベストシーズンを決める前の確認チェック", body: "季節の目安は、旅行先を選ぶための出発点です。実際の旅程は、渡航直前の天候・海況・交通・ホテルの営業状況を確認して仕上げましょう。", items: ["休みの日程が決まっている場合は、その月に海況が合う海岸か、内陸・高原のどれを主役にするか決める", "主役にした地域の天候・海況を、渡航直前に公式情報や現地情報で確認する", "国立公園、クルーズ、列車、祭り、寺院の営業・開催状況を公式情報で確認する", "雨や移動の遅れに備え、ホテル移動日と観光日を詰め込みすぎない", "高原・寺院・海辺のそれぞれに必要な服装と持ち物を分ける", "長距離移動と駅送迎は、季節に関わらず事前に手配を検討する", "予定を変える必要が出た際に、ホテルで休む日または近場の代替観光を一つ用意する"] },
    related: [{ before: "南西海岸を中心に旅程を組むなら、", text: "スリランカ旅行7日間モデルコース", href: "/articles/sri-lanka-7-day-itinerary", after: "を参考にしてください。" }, { before: "紅茶列車を主役にする時期・移動の組み方は、", text: "紅茶列車に乗るスリランカ旅行モデルコース", href: "/articles/sri-lanka-tea-train-itinerary", after: "で詳しく解説しています。" }, { before: "季節に合わせた移動手段の役割を比べるなら、", text: "スリランカの移動手段は何が正解？", href: "/articles/sri-lanka-transport-guide", after: "が役立ちます。" }],
    faqs: [{ question: "スリランカ旅行のベストシーズンはいつですか？", answer: "目的地と旅の目的で異なります。南西海岸を主役にするなら概ね12〜3月、東海岸を主役にするなら概ね5〜9月が検討の出発点です。文化三角地帯や高原、サファリは行き先ごとに条件が異なるため、渡航時の天候・海況・営業状況を確認しましょう。" }, { question: "日本の夏休みでもスリランカ旅行は楽しめますか？", answer: "楽しめます。5〜9月は南西側の雨を考慮しつつ、東海岸、北部、文化三角地帯を主役にする旅程を検討できます。海の活動は海況が重要なため、出発前に現地の営業と予報を確認してください。" }, { question: "南西海岸の海辺はいつ頃が穏やかですか？", answer: "スリランカ観光局は、南西海岸が11月から3月に晴天・穏やかな海になりやすいと案内しています。実際の海況は変わるため、渡航直前にも確認してください。" }, { question: "雨季にスリランカ旅行はできますか？", answer: "できます。地域によって天候の傾向が異なるため、海辺だけでなく遺跡や高原を組み合わせ、予定を固定しすぎない旅程にすると調整しやすくなります。海況が重要な体験は、代替案を用意してください。" }, { question: "紅茶列車やサファリを入れるなら、季節以外に何を確認すればよいですか？", answer: "列車は運行・予約状況と駅からホテルへの移動、サファリは公園の開園状況と早朝出発・終了後の移動を確認します。天候の目安だけでなく、現地での移動時間を確保することが大切です。" }],
    references: [{ label: "Sri Lanka Tourism: Pristine beach holidays", href: "https://www.srilanka.travel/pristine-beach-holidays" }, { label: "トリファ：スリランカのベストシーズンはいつ？月別気候とエリア別おすすめ時期を解説", href: "https://www.trifa.co/ja/column/preparation-tips-travel/srilanka-best-season" }, { label: "スリランカナビ：スリランカの観光ベストシーズンはいつ？各エリアの天候の特徴や服装もご紹介", href: "https://srilankanavi.com/blogs/117-%E3%82%B9%E3%83%AA%E3%83%A9%E3%83%B3%E3%82%AB%E3%81%AE%E8%A6%B3%E5%85%89%E3%83%99%E3%82%B9%E3%83%88%E3%82%B7%E3%83%BC%E3%82%BA%E3%83%B3%E3%81%AF%E3%81%84%E3%81%A4%EF%BC%9F%E5%90%84%E3%82%A8%E3%83%AA%E3%82%A2%E3%81%AE%E5%A4%A9%E5%80%99%E3%81%AE%E7%89%B9%E5%BE%B4%E3%82%84%E6%9C%8D%E8%A3%85%E3%82%82%E3%81%94%E7%B4%B9%E4%BB%8B%EF%BC%81" }, { label: "サラトラベル：月別に見るスリランカ観光のベストシーズン", href: "https://www.sara-tour.com/srilanka/info/column65.html" }, { label: "ジャスミンツアーズ：スリランカ旅行のベストシーズンは？", href: "https://srilanka-jasminetours.com/bestseason/" }],
  },
};

function Heading({ label, children }: { label: string; children: React.ReactNode }) { return <div className="mt-16 md:mt-20 mb-8"><span className="font-montserrat text-[10px] font-bold tracking-[0.22em]" style={{ color: "#E8732A" }}>{label}</span><h2 className="font-serif-jp text-2xl md:text-3xl font-bold leading-relaxed text-white mt-3">{children}</h2></div>; }

function TravelGuide({ variant }: { variant: "preparation" | "season" }) {
  const guide = guides[variant];
  useEffect(() => {
    document.title = guide.title;
    let meta = document.querySelector('meta[name="description"]') as HTMLMetaElement | null; if (!meta) { meta = document.createElement("meta"); meta.name = "description"; document.head.appendChild(meta); } meta.content = guide.description;
    let keywords = document.querySelector('meta[name="keywords"]') as HTMLMetaElement | null; if (!keywords) { keywords = document.createElement("meta"); keywords.name = "keywords"; document.head.appendChild(keywords); } keywords.content = guide.keywords;
    let canonical = document.getElementById("article-canonical") as HTMLLinkElement | null; if (!canonical) { canonical = document.createElement("link"); canonical.id = "article-canonical"; canonical.rel = "canonical"; document.head.appendChild(canonical); } canonical.href = `https://srilankataxicharter.com/articles/${guide.slug}`;
    const id = `article-guide-${guide.number}-jsonld`; document.getElementById(id)?.remove(); const jsonLd = document.createElement("script"); jsonLd.id = id; jsonLd.type = "application/ld+json"; jsonLd.text = JSON.stringify({ "@context": "https://schema.org", "@graph": [{ "@type": "Article", headline: guide.title, description: guide.description, mainEntityOfPage: canonical.href, inLanguage: "ja", image: `https://srilankataxicharter.com${guide.hero.src}` }, { "@type": "FAQPage", mainEntity: guide.faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) }] }); document.head.appendChild(jsonLd); return () => document.getElementById(id)?.remove();
  }, [guide]);
  return <div className="min-h-screen" style={{ backgroundColor: "#0A1520", color: "#F0F4F8" }}><MediaHeader activeCategory="travel-guide" /><main>
    <section className="relative overflow-hidden" style={{ minHeight: "min(640px, 74svh)" }}><img src={guide.hero.src} alt={guide.hero.alt} className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0" style={{ background: "linear-gradient(90deg, rgba(7,16,26,0.94) 0%, rgba(7,16,26,0.7) 52%, rgba(7,16,26,0.16) 100%), linear-gradient(0deg, #0A1520 0%, transparent 42%)" }} /><div className="relative z-10 max-w-6xl mx-auto px-5 md:px-8 min-h-[inherit] flex items-end pb-16 md:pb-20"><div className="max-w-3xl"><Link href="/articles/travel-guide" className="inline-flex items-center gap-2 mb-8 text-xs font-montserrat font-bold tracking-[0.12em] hover:text-white" style={{ color: "#B8C5D0" }}><ArrowLeft size={14} /> 個人旅行ガイドの記事一覧へ</Link><div className="flex items-center gap-3 mb-5"><span className="h-px w-12" style={{ backgroundColor: "#E8732A" }} /><span className="font-montserrat text-[10px] font-bold tracking-[0.24em]" style={{ color: "#F1A368" }}>INDEPENDENT TRAVEL · {guide.number}</span></div><h1 className="font-serif-jp text-3xl sm:text-4xl md:text-5xl font-semibold leading-[1.35] text-white mb-5">{guide.title}</h1><p className="font-sans text-sm md:text-base leading-8 max-w-2xl" style={{ color: "#D5E0E7" }}>{guide.hero.caption}</p><div className="flex items-center gap-4 mt-7 text-[11px] font-montserrat tracking-[0.1em]" style={{ color: "#B8C5D0" }}><span>個人旅行ガイド</span><span className="h-px w-5 bg-white/30" /><span>{guide.readingTime ?? "読了約10分"}</span></div></div></div></section>
    <article className="max-w-3xl mx-auto px-5 md:px-8 pb-24 md:pb-32"><div className="border-b py-11 md:py-14 space-y-7 md:space-y-8" style={{ borderColor: "rgba(255,255,255,0.14)" }}>{guide.intro.map((paragraph) => <p key={paragraph} className="font-serif-jp text-lg md:text-xl leading-9" style={{ color: "#DCE6EC" }}>{paragraph}</p>)}</div>
      <Heading label="PLAN AT A GLANCE">この記事の読み方</Heading><div className="flex flex-wrap items-center gap-y-3 font-sans text-sm leading-7" style={{ color: "#D5E0E7" }}>{guide.route.map((item, index) => <span key={`${guide.slug}-${index}-${item}`} className="inline-flex items-center">{index > 0 && <ArrowRight size={15} className="mx-3" style={{ color: "#E8732A" }} />}<span className="border px-3 py-2" style={{ borderColor: "rgba(232,115,42,0.45)", backgroundColor: "rgba(232,115,42,0.06)" }}>{item}</span></span>)}</div>
      <Heading label="VISUAL GUIDE">{guide.figure.title}</Heading><p className="font-sans text-[15px] leading-8 md:leading-9" style={{ color: "#C7D3DB" }}>{guide.figure.text}</p><figure className="mt-8 border p-2 md:p-3" style={{ borderColor: "rgba(232,115,42,0.38)", backgroundColor: "#0D1B28" }}><img src={guide.figure.src} alt={guide.figure.alt} className="w-full h-auto" loading="lazy" /><figcaption className="px-2 pt-3 pb-1 text-[11px] leading-6" style={{ color: "#8EA0AE" }}>{guide.figure.caption}</figcaption></figure>
      <Heading label="GUIDE">準備・季節を、実際の旅程に落とし込む</Heading><div className="space-y-16 md:space-y-20">{guide.sections.map((section) => <section key={section.label} className="border-l-2 pl-6 md:pl-8" style={{ borderColor: "#E8732A" }}><span className="font-montserrat text-[10px] font-bold tracking-[0.19em]" style={{ color: "#F1A368" }}>{section.label}</span><h2 className="font-serif-jp text-xl md:text-2xl font-bold leading-relaxed text-white mt-3 mb-5">{section.title}</h2><div className="space-y-6">{section.body.map((paragraph) => <p key={paragraph} className="font-sans text-[15px] leading-8 md:leading-9" style={{ color: "#C7D3DB" }}>{paragraph}</p>)}</div>{section.table && <div className="mt-8 overflow-x-auto border" style={{ borderColor: "rgba(232,115,42,0.35)" }}><table className="min-w-[720px] w-full text-left text-sm"><thead style={{ backgroundColor: "rgba(232,115,42,0.12)" }}><tr>{section.table.headers.map((header) => <th key={header} className="px-4 py-4 font-serif-jp text-sm text-white align-top">{header}</th>)}</tr></thead><tbody>{section.table.rows.map((row) => <tr key={row[0]} className="border-t" style={{ borderColor: "rgba(255,255,255,0.12)" }}>{row.map((cell, index) => <td key={`${row[0]}-${index}`} className="px-4 py-4 font-sans text-xs leading-6 align-top" style={{ color: index === 0 ? "#F1A368" : "#C7D3DB" }}>{cell}</td>)}</tr>)}</tbody></table></div>}{section.image && <figure className="mt-9 max-w-2xl"><div className="h-64 md:h-80 overflow-hidden" style={{ backgroundColor: "#132434" }}><img src={section.image.src} alt={section.image.alt} className="w-full h-full object-cover" loading="lazy" /></div><figcaption className="mt-3 text-[11px] leading-6" style={{ color: "#8EA0AE" }}>{section.image.caption}</figcaption></figure>}{section.links && <div className="mt-8 space-y-4 border-t pt-6" style={{ borderColor: "rgba(255,255,255,0.12)" }}>{section.links.map((link) => <p key={link.href} className="font-sans text-[15px] leading-8" style={{ color: "#C7D3DB" }}>{link.before}<Link href={link.href} className="underline decoration-[#E8732A] underline-offset-4 hover:text-white">{link.text}</Link>{link.after}</p>)}</div>}</section>)}</div>
      <section className="mt-16 md:mt-20 border p-7 md:p-9" style={{ borderColor: "rgba(232,115,42,0.5)", background: "linear-gradient(110deg, rgba(232,115,42,0.10), rgba(255,255,255,0.025))" }}><span className="font-montserrat text-[10px] font-bold tracking-[0.22em]" style={{ color: "#F1A368" }}>FINAL CHECK</span><h2 className="font-serif-jp text-2xl md:text-3xl font-bold leading-relaxed text-white mt-3">{guide.checklist.title}</h2><p className="font-sans text-[15px] leading-8 md:leading-9 mt-6" style={{ color: "#D7E1E7" }}>{guide.checklist.body}</p><ul className="mt-7 space-y-4 font-sans text-sm leading-7" style={{ color: "#D7E1E7" }}>{guide.checklist.items.map((item) => <li key={item} className="flex gap-3"><Check size={17} className="shrink-0 mt-1" style={{ color: "#E8732A" }} />{item}</li>)}</ul></section>
      <section className="mt-16 md:mt-20 space-y-6">{guide.related.map((link) => <p key={link.href} className="font-sans text-[15px] leading-8 md:leading-9" style={{ color: "#C7D3DB" }}>{link.before}<Link href={link.href} className="underline decoration-[#E8732A] underline-offset-4 hover:text-white">{link.text}</Link>{link.after}</p>)}</section>
      <Heading label="FAQ">よくある質問</Heading><div className="divide-y border-y" style={{ borderColor: "rgba(255,255,255,0.14)" }}>{guide.faqs.map((faq, index) => <details key={faq.question} className="group py-6"><summary className="cursor-pointer list-none flex items-start gap-4 font-serif-jp font-bold text-white"><span className="font-montserrat text-[10px] tracking-[0.16em] mt-1" style={{ color: "#E8732A" }}>Q{String(index + 1).padStart(2, "0")}</span><span className="flex-1 leading-7">{faq.question}</span><span className="text-xl leading-none transition-transform group-open:rotate-45" style={{ color: "#E8732A" }}>+</span></summary><p className="font-sans text-sm leading-8 mt-5 pl-10" style={{ color: "#C7D3DB" }}>{faq.answer}</p></details>)}</div>
      <section className="relative overflow-hidden mt-16 md:mt-20 p-7 md:p-10 border" style={{ borderColor: "rgba(232,115,42,0.55)", background: "linear-gradient(110deg, rgba(232,115,42,0.16), rgba(201,168,76,0.10) 48%, rgba(9,22,34,0.65)), #102132" }}><div className="absolute inset-0 opacity-20" style={{ backgroundImage: "linear-gradient(90deg, rgba(255,255,255,0.06) 1px, transparent 1px), linear-gradient(rgba(255,255,255,0.06) 1px, transparent 1px)", backgroundSize: "22px 22px" }} /><div className="relative z-10 max-w-2xl"><div className="flex items-center gap-3 mb-4"><span className="h-px w-10" style={{ backgroundColor: "#E8732A" }} /><span className="font-montserrat text-[10px] font-bold tracking-[0.22em]" style={{ color: "#F1A368" }}>MAKE THE PLAN SIMPLE</span></div><h2 className="font-serif-jp text-2xl md:text-3xl font-bold text-white leading-relaxed">旅程と移動を、<br />出発前に整えよう。</h2><p className="font-sans text-sm md:text-base leading-8 mt-5" style={{ color: "#D7E1E7" }}>料金の分かりやすさ、日本語対応、ドライバー品質、キャンセル条件を比べて、スリランカ個人旅行に合うタクシーチャーターを選びませんか。</p><a href="/#ranking" className="inline-flex items-center gap-3 mt-7 px-6 py-4 font-montserrat text-xs font-bold tracking-[0.12em] text-white transition-transform hover:-translate-y-0.5" style={{ backgroundColor: "#E8732A", boxShadow: "0 12px 26px rgba(0,0,0,0.25)" }}>タクシーチャーターおすすめ3選を比較する <ArrowRight size={15} /></a></div></section>
      <section className="mt-14 border-t pt-8" style={{ borderColor: "rgba(255,255,255,0.14)" }}><h2 className="font-serif-jp text-lg font-bold text-white mb-4">参考情報</h2><ol className="space-y-2 font-sans text-xs leading-6" style={{ color: "#9BAAB5" }}>{guide.references.map((reference, index) => <li key={reference.href}>[{index + 1}] <a className="underline underline-offset-4 hover:text-white" href={reference.href} target="_blank" rel="noopener noreferrer">{reference.label}</a></li>)}</ol></section>
    </article></main></div>;
}

export function ArticleIndependentTravelPreparation() { return <TravelGuide variant="preparation" />; }
export function ArticleBestSeasonByRegion() { return <TravelGuide variant="season" />; }
